[workspace]
resolver = "2"
members = [
    "crates/qchain-crypto",
    "crates/qchain-core",
    "crates/qchain-storage",
    "crates/qchain-execution",
    "crates/qchain-governance",
    "crates/qchain-consensus",
    "crates/qchain-simulation",
    "crates/qchain-stark",
    "crates/qchain-network",
    "crates/qchain-node",
    "crates/qchain-cli",
    "crates/qchain-faucet",
]

[workspace.package]
version = "0.1.0"
edition = "2021"

[workspace.dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"
borsh = { version = "1", features = ["derive"] }
sha3 = "0.10"
bs58 = "0.5"
ed25519-dalek = { version = "2", features = ["rand_core"] }
oqs = { version = "0.11", default-features = false, features = ["ml_dsa", "sphincs", "vendored", "std"] }
rand = "0.8"
anyhow = "1"
thiserror = "1"
tokio = { version = "1", features = ["full"] }
axum = "0.7"
clap = { version = "4", features = ["derive"] }
reqwest = { version = "0.12", features = ["json", "blocking"] }
hex = "0.4"
wasmtime = "27"
wat = "1"
tracing = "0.1"
tracing-subscriber = "0.3"
winterfell = "0.13"
