[package]
name = "supersol-node"
version.workspace = true
edition.workspace = true

[dependencies]
supersol-crypto = { path = "../supersol-crypto" }
supersol-core = { path = "../supersol-core" }
supersol-runtime = { path = "../supersol-runtime" }

serde.workspace = true
serde_json.workspace = true
tokio.workspace = true
axum.workspace = true
clap.workspace = true
anyhow.workspace = true
rand.workspace = true
hex.workspace = true
