[package]
name = "qchain-wallet"
version.workspace = true
edition.workspace = true

[[bin]]
name = "qchain-wallet"
path = "src/main.rs"

[dependencies]
qchain-core = { path = "../qchain-core" }
qchain-crypto = { path = "../qchain-crypto" }
qchain-execution = { path = "../qchain-execution" }
qchain-governance = { path = "../qchain-governance" }
serde.workspace = true
serde_json.workspace = true
borsh.workspace = true
tokio.workspace = true
axum.workspace = true
reqwest.workspace = true
clap.workspace = true
anyhow.workspace = true
hex.workspace = true
base64 = "0.22"
qrcode = { version = "0.14", default-features = false, features = ["svg"] }
aes-gcm = "0.10"
argon2 = "0.5"
rand = "0.8"
sha3.workspace = true
subtle = "2"
