[package]
name = "qchain-stark"
version.workspace = true
edition.workspace = true

[dependencies]
winterfell.workspace = true
thiserror.workspace = true
qchain-core = { path = "../qchain-core" }
qchain-storage = { path = "../qchain-storage" }

[dev-dependencies]
qchain-crypto = { path = "../qchain-crypto" }
