[package]
name = "supersol-crypto"
version.workspace = true
edition.workspace = true

[dependencies]
serde.workspace = true
serde_json.workspace = true
borsh.workspace = true
ed25519-dalek.workspace = true
rand.workspace = true
bs58.workspace = true
anyhow.workspace = true
hex.workspace = true
sha2.workspace = true
fips204 = "0.4.6"
